// Code generated by http://github.com/gojuno/minimock (v3.3.10). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/Genvekt/cli-chat/services/chat-server/internal/model"
	"github.com/gojuno/minimock/v3"
)

// MessageRepositoryMock implements repository.MessageRepository
type MessageRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, message *model.Message) (err error)
	inspectFuncCreate   func(ctx context.Context, message *model.Message)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mMessageRepositoryMockCreate
}

// NewMessageRepositoryMock returns a mock for repository.MessageRepository
func NewMessageRepositoryMock(t minimock.Tester) *MessageRepositoryMock {
	m := &MessageRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mMessageRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*MessageRepositoryMockCreateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMessageRepositoryMockCreate struct {
	optional           bool
	mock               *MessageRepositoryMock
	defaultExpectation *MessageRepositoryMockCreateExpectation
	expectations       []*MessageRepositoryMockCreateExpectation

	callArgs []*MessageRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// MessageRepositoryMockCreateExpectation specifies expectation struct of the MessageRepository.Create
type MessageRepositoryMockCreateExpectation struct {
	mock      *MessageRepositoryMock
	params    *MessageRepositoryMockCreateParams
	paramPtrs *MessageRepositoryMockCreateParamPtrs
	results   *MessageRepositoryMockCreateResults
	Counter   uint64
}

// MessageRepositoryMockCreateParams contains parameters of the MessageRepository.Create
type MessageRepositoryMockCreateParams struct {
	ctx     context.Context
	message *model.Message
}

// MessageRepositoryMockCreateParamPtrs contains pointers to parameters of the MessageRepository.Create
type MessageRepositoryMockCreateParamPtrs struct {
	ctx     *context.Context
	message **model.Message
}

// MessageRepositoryMockCreateResults contains results of the MessageRepository.Create
type MessageRepositoryMockCreateResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mMessageRepositoryMockCreate) Optional() *mMessageRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) Expect(ctx context.Context, message *model.Message) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &MessageRepositoryMockCreateParams{ctx, message}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx

	return mmCreate
}

// ExpectMessageParam2 sets up expected param message for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectMessageParam2(message *model.Message) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.message = &message

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) Inspect(f func(ctx context.Context, message *model.Message)) *mMessageRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for MessageRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) Return(err error) *MessageRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &MessageRepositoryMockCreateResults{err}
	return mmCreate.mock
}

// Set uses given function f to mock the MessageRepository.Create method
func (mmCreate *mMessageRepositoryMockCreate) Set(f func(ctx context.Context, message *model.Message) (err error)) *MessageRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the MessageRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the MessageRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the MessageRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mMessageRepositoryMockCreate) When(ctx context.Context, message *model.Message) *MessageRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	expectation := &MessageRepositoryMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &MessageRepositoryMockCreateParams{ctx, message},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up MessageRepository.Create return parameters for the expectation previously defined by the When method
func (e *MessageRepositoryMockCreateExpectation) Then(err error) *MessageRepositoryMock {
	e.results = &MessageRepositoryMockCreateResults{err}
	return e.mock
}

// Times sets number of times MessageRepository.Create should be invoked
func (mmCreate *mMessageRepositoryMockCreate) Times(n uint64) *mMessageRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of MessageRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	return mmCreate
}

func (mmCreate *mMessageRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements repository.MessageRepository
func (mmCreate *MessageRepositoryMock) Create(ctx context.Context, message *model.Message) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, message)
	}

	mm_params := MessageRepositoryMockCreateParams{ctx, message}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := MessageRepositoryMockCreateParams{ctx, message}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter message, want: %#v, got: %#v%s\n", *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the MessageRepositoryMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, message)
	}
	mmCreate.t.Fatalf("Unexpected call to MessageRepositoryMock.Create. %v %v", ctx, message)
	return
}

// CreateAfterCounter returns a count of finished MessageRepositoryMock.Create invocations
func (mmCreate *MessageRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of MessageRepositoryMock.Create invocations
func (mmCreate *MessageRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to MessageRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mMessageRepositoryMockCreate) Calls() []*MessageRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*MessageRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *MessageRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *MessageRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageRepositoryMock.Create with params: %#v", *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to MessageRepositoryMock.Create")
		} else {
			m.t.Errorf("Expected call to MessageRepositoryMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Error("Expected call to MessageRepositoryMock.Create")
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageRepositoryMock.Create but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), afterCreateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MessageRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MessageRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MessageRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
