version: '3'

volumes:
  chat-server_postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    container_name: chat-server_pg
    env_file:
      - prod.env
    ports:
      - "54322:5432"
    volumes:
      - chat-server_postgres_volume:/var/lib/postgresql/data
    networks:
      - chat-server

  migrator:
    container_name: chat-server_migrator
    image: ${MIGRATOR_IMAGE}
    build:
      context: .
      dockerfile: migrator/migrator-prod.Dockerfile
    env_file:
      - prod.env
    restart: on-failure
    networks:
      - chat-server

networks:
  chat-server:
    external: true