name: DB for auth service
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'services/auth'
      - 'services/auth/db/postgres/migrations'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'services/auth'
      - 'services/auth/db/postgres/migrations'

jobs:
  build:
    name: Build migrator
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: echo "${{ secrets.AUTH_POSTGRES_ENV_FILE }}" > services/auth/db/postgres/prod.env
      - name: Log .env file
        run: cat services/auth/db/postgres/prod.env