name: DB for auth service
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'services/auth/**'
      - 'services/auth/db/postgres/migrations/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'services/auth/**'
      - 'services/auth/db/postgres/migrations/**'

env:
  DB_DIR: services/auth/db/postgres

jobs:
  build:
    name: Build migrator
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch ${{ env.DB_DIR }}/prod.env
          echo "${{ secrets.AUTH_POSTGRES_ENV_FILE }}" > ${{ env.DB_DIR }}/prod.env
      - name: Log .env file
        run: cat ${{ env.DB_DIR }}/prod.env