name: kafka
on:
  push:
    branches:
      - main
    paths:
      - 'services/kafka/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/kafka/**'

env:
  DIR: services/kafka
  DOCKER_REGISTRY_URL: cr.selcloud.ru/genvekt-cli-chat

jobs:
  deploy:
    name: Deploy Kafka to Selectel Cloud
    if: ${{ github.event_name != 'pull_request'}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Send docker compose to Selectel server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{secrets.SSH_USERNAME}}
          port: 22
          key: ${{secrets.SSH_KEY}}
          source: "${{ env.DIR }}/docker-compose.yaml"
          target: "~/.deploy/"

      - name: Run DB and Migrate
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          envs: APPTOKEN,USERNAME
          script: |
            # Login into Selectel Registry
            docker login -u ${{secrets.DOCKER_REGISTRY_USERNAME}} -p ${{secrets.DOCKER_REGISTRY_PASSWORD}} ${{env.DOCKER_REGISTRY_URL}}
            cd ~/.deploy/${{ env.DIR }}
            docker-compose -f ./docker-compose.yaml up -d