name: closer library
on:
  push:
    branches:
      - main
    paths:
      - 'libraries/closer/**'
  pull_request:
    paths:
      - 'libraries/closer/**'

env:
  LIBRARY_PATH: ./libraries/closer

jobs:
  test:
    name: Test library
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum

      - name: Test
        run: go test -C $LIBRARY_PATH ./...

  linter:
    name: Lint library
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59
          working-directory: ${{ env.LIBRARY_PATH }}
          args: --timeout=30m --config=../../.golangci.pipeline.yaml
          skip-cache: true